### ISSUE TITLE
NullPointerException in FloatingFolder$3.onItemClick(FloatingFolder.java:132)

### ISSUE THREAD

**Issue by ghost** [pingpongboss/StandOut#1]
I was just playing around a little bit when this happend:

06-15 10:59:37.395: E/AndroidRuntime(13491): FATAL EXCEPTION: main
06-15 10:59:37.395: E/AndroidRuntime(13491): java.lang.NullPointerException
06-15 10:59:37.395: E/AndroidRuntime(13491):    at wei.mark.example.floatingfolders.FloatingFolder$3.onItemClick(FloatingFolder.java:132)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at wei.mark.standout.StandOutWindow$7.onTouch(StandOutWindow.java:1640)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.view.View.dispatchTouchEvent(View.java:3928)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:943)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:994)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:994)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:994)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2328)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.view.ViewRoot.handleMessage(ViewRoot.java:1958)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.os.Looper.loop(Looper.java:143)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at android.app.ActivityThread.main(ActivityThread.java:4196)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at java.lang.reflect.Method.invokeNative(Native Method)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at java.lang.reflect.Method.invoke(Method.java:507)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
06-15 10:59:37.395: E/AndroidRuntime(13491):    at dalvik.system.NativeStart.main(Native Method)

**Comment by pingpongboss** [comment]
please confirm that you can reproduce this bug on latest. Also, a description of the last actions you took would help.
