### ISSUE TITLE
ActivityNotFoundException at FloatingFolder$6.onClick(FloatingFolder.java:336)

### ISSUE THREAD

**Issue by ghost** [pingpongboss/StandOut#3]
I added the android contacts icon to the folder and clicked on it:

06-15 11:08:24.349: E/AndroidRuntime(13911): FATAL EXCEPTION: main
06-15 11:08:24.349: E/AndroidRuntime(13911): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.htccontacts/com.android.internal.app.ResolverActivity}; have you declared this activity in your AndroidManifest.xml?
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1565)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.app.ContextImpl.startActivity(ContextImpl.java:679)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.content.ContextWrapper.startActivity(ContextWrapper.java:258)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at wei.mark.example.floatingfolders.FloatingFolder$6.onClick(FloatingFolder.java:336)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.view.View.performClick(View.java:2532)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.view.View$PerformClick.run(View.java:9277)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.os.Handler.handleCallback(Handler.java:587)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.os.Handler.dispatchMessage(Handler.java:92)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.os.Looper.loop(Looper.java:143)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at android.app.ActivityThread.main(ActivityThread.java:4196)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at java.lang.reflect.Method.invokeNative(Native Method)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at java.lang.reflect.Method.invoke(Method.java:507)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
06-15 11:08:24.349: E/AndroidRuntime(13911):    at dalvik.system.NativeStart.main(Native Method)

**Comment by pingpongboss** [comment]
Can you reproduce this bug with latest?

Also, does this happen with every app, or just com.android.htccontacts?
